language: cpp
compiler: gcc
env:
  global:
  - APT_DEPENDENCIES="doxygen doxygen-latex libboost-all-dev libeigen3-dev 
    liblapack-dev libblas-dev gfortran python-dev python-sphinx python-numpy 
    libbullet-dev
    ros-hydro-angles
    ros-hydro-cmake-modules
    ros-hydro-common-msgs
    ros-hydro-control-msgs
    ros-hydro-geometry-msgs
    ros-hydro-pr2-controllers-msgs
    ros-hydro-pr2-mechanism
    ros-hydro-pr2-controllers
    ros-hydro-resource-retriever
    ros-hydro-realtime-tools
    ros-hydro-robot-state-publisher
    ros-hydro-ros-control
    ros-hydro-tf
    ros-hydro-urdf
    ros-hydro-urdfdom-py"
  - GIT_DEPENDENCIES="jrl-umi3218/jrl-mathtools jrl-umi3218/jrl-mal laas/abstract-robot-dynamics jrl-umi3218/jrl-dynamics
    stack-of-tasks/dynamic-graph  stack-of-tasks/dynamic-graph-python 
    stack-of-tasks/sot-core       stack-of-tasks/sot-tools 
    stack-of-tasks/sot-dynamic    stack-of-tasks/sot-application
    francois-keith/jrl_dynamics_urdf:topic/fixed_joints"
  - ROS_DISTRO=hydro
  - ROS_GIT_DEPENDENCIES="francois-keith/dynamic_graph_bridge_msgs:catkin
    francois-keith/dynamic_graph_bridge:catkin"
  - ALLOW_CATKINLINT_FAILURE=true
notifications:
  email:
  - francois.keith@gmail.com
branches:
  only:
  - master
  - groovy
  - catkin
before_install: ./.travis/run dependencies/catkin; ./.travis/run before_install
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure

